version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - C:\Users\victor.machado\Desktop\log-monitor\Logs:/app/Logs
